### ISSUE TITLE
How to call smart contract functions? 

### ISSUE THREAD

**Issue by MiracleWeb3** [MultipleChain/tron-walletconnect#1]
There is problems with defining contract instances, and calling functions from them, it can't do that, I don't know why, matter fact I tried with simple tronlink-tronweb and same code works for it, I am sure 100% that calling function from smart contract with triggerSmartContract will create unsignedTransaction that user (100% sure) able to Sign in his wallet app, so I'm kinda stuck because I can't achieve that functionality.

Any ideas on how to?

**Comment by 0xBeycan** [comment]
Hello, sorry for the late reply, if you examine the multiplechain/tron package, you will understand how it works, first you should create the rawtx with tronweb and then sign it with the signTransaction method in the incoming provider after the connection is established and then send the transaction with the tronweb sendRawTransaction method.

There are links below.

https://github.com/MultipleChain/js/blob/83540b1bd136c425ee03c16ecd3cf597f2ae1362/packages/networks/tron/src/assets/Token.ts#L88
https://github.com/MultipleChain/js/blob/83540b1bd136c425ee03c16ecd3cf597f2ae1362/packages/networks/tron/src/browser/Wallet.ts#L206

**Comment by MiracleWeb3** [comment]
Hey thank you a lot, solved problem already, it was actually caused by use of "tronWeb.trx.signTransaction" instead of "wallet.SignTransaction" which is only method for walletconnect-tron.

I hate tronweb tbh, it caused so much pain in the ass.
